# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerosrc', models.CharField(default=b'1000', max_length=50)),
                ('addresssrc', models.CharField(default=b'192.168.3.5', max_length=12)),
                ('numerodest', models.CharField(default=b'1010', max_length=30)),
                ('addressdest', models.CharField(default=b'192.168.3.6', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='address',
            field=models.CharField(default=b'168.85.69.4', max_length=12),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(default=b'Machine 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='password',
            field=models.CharField(default=b'****', max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='username',
            field=models.CharField(default=b'Foulen', max_length=30),
        ),
    ]
