# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_auto_20160321_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='prefix',
            field=models.CharField(default=b'1', max_length=30),
        ),
    ]
