# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_machine_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='prefix',
        ),
        migrations.AddField(
            model_name='machine',
            name='prefix_freeswitch',
            field=models.CharField(default=b'1', max_length=8),
        ),
    ]
