# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_auto_20160323_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['Name_machine']},
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='address',
            new_name='Address_machine',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='password',
            new_name='Password_machine',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='username',
            new_name='Username_machine',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='prefix_freeswitch',
        ),
        migrations.AddField(
            model_name='machine',
            name='Name_machine',
            field=models.CharField(default=b'Machine 1', max_length=30),
        ),
        migrations.AddField(
            model_name='machine',
            name='Prefix_freeswitch',
            field=models.CharField(default=b'1', max_length=5),
        ),
    ]
