# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0009_auto_20160426_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='Prefix_freeswitch',
            field=models.CharField(blank=True, default=b'1', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='address',
            field=models.CharField(blank=True, default=b'168.85.69.4', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, default=b'Machine 1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='password',
            field=models.CharField(blank=True, default=b'****', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='username',
            field=models.CharField(blank=True, default=b'Foulen', max_length=30, null=True),
        ),
    ]
