# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0011_auto_20160426_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='password',
            field=models.CharField(default=b'****', max_length=30, null=True),
        ),
    ]
